# -*- coding: utf-8 -*-
"""Hora+da+pratica.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TbQ5Ht0zX_Pb8U757Uv3iThfc3VB5RSM

# Sobre o notebook

A "hora da prática" é uma atividade do curso de Python para Data Science da Alura que contém diversos desafios envolvendo os aprendizados de cada aula.

O notebook "hora da pratica" é um notebook construído com espaço para as células dos desafios propostos no curso, com ele você tem espaço para construir e executar suas soluções

## Aula 1 - Introdução ao Python

### Questão 1

Imprima a frase `Escola de Dados da Alura!`
"""

print('Escola de Dados da Alura!')

"""### Questão 2
Imprima na tela seu nome e seu sobrenome seguindo a estrutura abaixo:
```
Nome: [seu nome]
Sobrenome: [seu sobrenome]
```

"""

print('Nome: Lucas \nSobrenome: Rossini')

"""### Questão 3
Imprima o seu primeiro nome letra a letra. Por exemplo, nome é Mirla, então eu obtenho a seguinte saída:
```
M
I
R
L
A
```

"""

print('L \nU \nC \nA \nS')

"""### Questão 4
Imprima o dia do seu nascimento em formato `dia mês ano`. Os valores de dia e ano não podem estar entre aspas. O formato deve estar como no exemplo, supondo uma data de aniversário dia 28 de fevereiro de 2003:
```
28 fevereiro 2003
```
"""

print(20, 'Abril', 2009)

"""### Questão 5
Imprima em um único print o atual ano que você está fazendo esse curso, o valor do ano deve ser um dado numérico. A saída do print deve ser a seguinte:
```
Ano atual: [ano]
```

"""

ano = 2026
print(f'Ano atual: {ano}')

"""## Aula 2 - Manipulando dados no Python

### Coleta e amostragem de dados

#### Questão 1
Crie um programa que solicite à pessoa usuária digitar seu nome, e imprima “Olá, [nome]!”.
"""

nome = input('Qual o seu nome?')
print('Olá,', nome)

"""#### Questão 2
Crie um programa que solicite à pessoa usuária digitar seu nome e idade, e imprima “Olá, [nome], você tem [idade] anos.”.
"""

nome = input('Qual o seu nome?')
idade = int(input('Qual a sua idade?'))
print(f'Olá, {nome}, você tem {idade} anos')

"""#### Questão 3
Crie um programa que solicite à pessoa usuária digitar seu nome, idade e altura em metros, e imprima “Olá, [nome], você tem [idade] anos e mede [altura] metros!”.
"""

nome = input('Digite seu nome: ')
idade = int(input('Digite sua idade: '))
altura = float(input('Digite sua altura: '))
print(f'Olá, {nome}, você tem {idade} anos e mede {altura} metros.')

"""### Calculadora com operadores

#### Questão 1

Crie um programa que solicite dois valores numéricos à pessoa usuária e imprima a soma dos dois valores.
"""

n1 = int(input("Digite um valor: "))
n2 = int(input("Digite um valor: "))
print(n1 + n2)

"""#### Questão 2
Crie um programa que solicite três valores numéricos à pessoa usuária e imprima a soma dos três valores.
"""

n1 = int(input("Digite um valor: "))
n2 = int(input("Digite um valor: "))
n3= int(input("Digite um valor: "))
print(n1 + n2 + n3)

"""#### Questão 3
Crie um programa que solicite dois valores numéricos à pessoa usuária e imprima a subtração do primeiro pelo o segundo valor.
"""

n1 = int(input("Digite um valor: "))
n2 = int(input("Digite um valor: "))
print(n1 - n2)

"""#### Questão 4

Crie um programa que solicite dois valores numéricos à pessoa usuária e imprima a multiplicação dos dois valores.

"""

n1 = int(input("Digite um valor: "))
n2 = int(input("Digite um valor: "))
print(n1 * n2)

"""#### Questão 5

Crie um programa que solicite dois valores numéricos, um numerador e um denominador, e realize a divisão entre os dois valores. Deixe claro que o valor do denominador não pode ser `0`.

"""

n1 = int(input("Digite um valor: "))
n2 = int(input("Digite um valor: "))
print((n1 / n2))

"""#### Questão 6

Crie um programa que solicite dois valores numéricos, um operador e uma potência, e realize a exponenciação entre esses dois valores.

"""

n1 = int(input("Digite um valor: "))
n2 = int(input("Digite um valor: "))
print(n1 ** n2)

"""#### Questão 7
Crie um programa que solicite dois valores numéricos, um numerador e um denominador e realize a divisão inteira entre os dois valores. Deixe claro que o valor do denominador não pode ser `0`.
"""

n1 = int(input("Digite um valor: "))
n2 = int(input("Digite um valor: "))
print(int(n1 / n2))

"""#### Questão 8

Crie um programa que solicite dois valores numéricos, um numerador e um denominador, e retorne o resto da divisão entre os dois valores. Deixe claro que o valor do denominador não pode ser `0`.
"""

n1 = int(input("Digite um valor: "))
n2 = int(input("Digite um valor: "))
print(n1 % n2)

"""#### Questão 9

Crie um código que solicita 3 notas de um estudante e imprima a média das notas.
"""

n1 = int(input("Digite a primeira nota: "))
n2 = int(input("Digite a segunda nota: "))
n3 = int(input("Digite a terceira nota: "))
media = ((n1 + n2 + n3)/3)
print(float(media))

"""#### Questão 10

Crie um código que calcule e imprima a média ponderada dos números 5, 12, 20 e 15 com pesos respectivamente iguais a 1, 2, 3 e 4.
"""

media = ((5*1 + 12*2 + 20 * 3 + 15* 4)/4)
print(float(media))

"""### Editando textos

#### Questão 1

Crie uma variável chamada “`frase`” e atribua a ela uma string de sua escolha. Em seguida, imprima a frase na tela.
"""

frase = str('Alura')
print(frase)

"""#### Questão 2
Crie um código que solicite uma frase e depois imprima a frase na tela.
"""

frase = str(input('Escreva a palavra "Alura": '))
print(frase)

"""#### Questão 3

Crie um código que solicite uma frase à pessoa usuária e imprima a mesma frase digitada mas com todas as letras maiúsculas.
"""

frase = (input('Escreva a palavra "Alura": '))
print(frase.upper())

"""#### Questão 4

Crie um código que solicite uma frase à pessoa usuária e imprima a mesma frase digitada mas com todas as letras minúsculas.
"""

frase = (input('Escreva a palavra "Alura": '))
print(frase.lower())

"""#### Questão 5

Crie uma variável chamada “`frase`” e atribua a ela uma string de sua escolha. Em seguida, imprima a frase sem espaços em branco no início e no fim.
"""

frase = '   Escreva a palavra "Alura"   '
print(frase.strip())

"""#### Questão 6

Crie um código que solicite uma frase à pessoa usuária e imprima a mesma frase sem espaços em branco no início e no fim.
"""

frase = (input('Escreva a frase " Essa frase tem espaços": '))
print(frase.strip())

"""#### Questão 7


Crie um código que solicite uma frase à pessoa usuária e imprima a mesma frase sem espaços em branco no início e no fim e em letras minúsculas.
"""

frase = (input('Escreva a frase " Essa frase tem espaços": '))
print(frase.strip().lower())

"""#### Questão 8

Crie um código que solicite uma frase à pessoa usuária e imprima a mesma frase com todas as vogais “`e`” trocadas pela letra “`f`”.
"""

frase = (input('Escreva a frase " Estamos enlouquecidos": '))
print(frase.replace('e', 'f'))

"""#### Questão 9


Crie um código que solicite uma frase à pessoa usuária e imprima a mesma frase com todas as vogais “`a`” trocadas pela caractere  “`@`”.
"""

frase = (input('Escreva a frase " Estamos enlouquecidos": '))
print(frase.replace('e', '@').replace('E', '@'))

"""#### Questão 10


Crie um código que solicite uma frase à pessoa usuária e imprima a mesma frase com todas as consoantes “`s`” trocadas pelo caractere  “`$`”.
"""

frase = (input('Escreva a frase " Estamos enlouquecidos": '))
print(frase.replace('s', '$'))

"""## Aula 3 - Estruturas condicionais

### Aquecendo na programação

#### Questão 1
Escreva um programa que peça à pessoa usuária para fornecer dois números e exibir o número maior.
"""

n1 = int(input('Fornaça um número: '))
n2 = int(input('Fornaça outro número: '))
if n1 > n2:
  print(n1)
else:
  print(n2)

"""#### Questão 2
Escreva um programa que solicite o percentual de crescimento de produção de uma empresa e informe se houve um crescimento (porcentagem positiva) ou decrescimento (porcentagem negativa).
"""

n1 = int(input('Informe o porcentual de crescimento de produção da empresa: '))
if n1 > 0:
  print(f'Houve um crescimento')
else:
  print(f'Houve um decrescimento')

"""#### Questão 3
Escreva um programa que determine se uma letra fornecida pela pessoa usuária é uma vogal ou consoante.
"""

l1 = str(input('Forneça uma letra: '))

if l1 == 'a':
  print('Vogal')
elif l1 == 'e':
  print('Vogal')
elif l1 == 'i':
  print('Vogal')
elif l1 == 'o':
  print('Vogal')
elif l1 == 'u':
  print('Vogal')
else:
  print('Consoante')

"""#### Questão 4
Escreva um programa que leia valores médios de preços de um modelo de carro por 3 anos consecutivos e exiba o valor mais alto e mais baixo entre esses três anos.
"""

v1 = int(input('Insira valor medio do primeiro ano: '))
v2 = int(input('Insira valor medio do segundo ano: '))
v3 = int(input('Insira valor medio do terceiro ano: '))
maior = v1
if v2 > maior:
  maior = v2
if v3 > maior:
  maior = v3
menor = v1
if v2 < menor:
  menor = v2
if v3 < menor:
  menor = v3
print(f'O maior valor é {maior}')
print(f'O menor valor é {menor}')

"""#### Questão 5
Escreva um programa que pergunte sobre o preço de três produtos e indique qual é o produto mais barato para comprar.
"""

p1 = int(input('Insira o valor do produto x: '))
p2 = int(input('Insira o valor do produto y: '))
p3 = int(input('Insira o valor do produto z: '))
if p1<p2 and p1<p3:
  print('O primeiro produto é o mais barato')
if p2<p1 and p2<p3:
  print('O segundo produto é o mais barato')
if p3<p2 and p3<p1:
  print('O terceiro produto é o mais barato')

"""#### Questão 6
Escreva um programa que leia três números e os exiba em ordem decrescente.
"""

n1 = int(input('Insira o valor x: '))
n2 = int(input('Insira o valor y: '))
n3 = int(input('Insira o valor z: '))
if n1>=n2 and n1>=n3:
  print(n1)
  if n2>=n3:
    print(f'{n2}\n{n3}')
  else:
    print(f'{n3}\n{n2}')
elif n2>=n1 and n2>=n3:
  print(n2)
  if n1>=n3:
    print(f'{n1}\n{n3}')
  else:
    print(f'{n3}\n{n1}')
else:
   print(n3)
   if n2>=n1:
    print(f'{n2}\n{n1}')
   else:
    print(f'{n1}\n{n2}')

"""#### Questão 7
Escreva um programa que pergunte em qual turno a pessoa usuária estuda ("manhã", "tarde" ou "noite") e exiba a mensagem "Bom Dia!", "Boa Tarde!", "Boa Noite!", ou "Valor Inválido!", conforme o caso.
"""

turno = input('Você trabalha no turno da manhã, tarde ou noite? ')
if turno == 'manhã':
  print('Bom dia!')
elif turno == 'tarde':
  print('Boa tarde!')
elif turno == 'noite':
  print('Boa noite!')
else:
  print('Valor Inválido!')

"""#### Questão 8
Escreva um programa que peça um número inteiro à pessoa usuária e determine se ele é par ou ímpar. Dica: Você pode utilizar o operador módulo `%`.
"""

n = int(input('Insira um número: '))
if n % 2 == 0:
  print('Par')
else:
  print('Ímpar')

"""#### Questão 9
Escreva um programa que peça um número à pessoa usuária e informe se ele é inteiro ou decimal.
"""

n = float(input('Insira um número: '))
if n % 1 == 0:
  print('Inteiro')
else:
  print('Decimal')

"""### Momento dos projetos"""



"""#### Questão 10
Um programa deve ser escrito para ler dois números e, em seguida, perguntar à pessoa usuária qual operação ele deseja realizar. O resultado da operação deve incluir informações sobre o número - se é par ou ímpar, positivo ou negativo e inteiro ou decimal.
"""

n1 = float(input('Insira um número: '))
n2 = float(input('Insira outro número: '))
operacao = input('Qual operação você deseja fazer? [soma, subtração, multiplicação, divisão, potenciação] ')
if operacao == 'soma':
  resultado = n1 + n2
  print(resultado)
elif operacao == 'subtração':
  resultado = n1 - n2
  print(resultado)
elif operacao == 'multiplicação':
  resultado = n1 * n2
  print(resultado)
elif operacao == 'divisão':
  resultado = n1/n2
  print(resultado)
elif operacao == 'potenciação':
  resultado = n1 ** n2
  print(resultado)
else:
  print('Operação inválida')
if resultado % 2 == 0:
  print('Número Par')
else:
  print('Número Ímpar')
if resultado >=0:
  print('Número positivo')
else:
  print('Número negativo')
if resultado % 1 == 0:
  print('Número Inteiro')
else:
  print('Número Decimal')

"""#### Questão 11
Escreva um programa que peça à pessoa usuária três números que representam os lados de um triângulo. O programa deve informar se os valores podem ser utilizados para formar um triângulo e, caso afirmativo, se ele é equilátero, isósceles ou escaleno. Tenha em mente algumas dicas:
- Três lados formam um triângulo quando a soma de quaisquer dois lados for maior que o terceiro;
- Triângulo Equilátero: três lados iguais;
- Triângulo Isósceles: quaisquer dois lados iguais;
- Triângulo Escaleno: três lados diferentes;

"""

l1 = float(input('Insira o primeiro lado: '))
l2 = float(input('Insira o segundo lado: '))
l3 = float(input('Insira o terceiro lado: '))
if l1+l2>l3 or l1+l3>l2 or l2+l3>l1:
  if l1==l2==l3:
    print('O triângulo é equilátero')
  elif l1==l2!=l3 or l2==l3!=l1 or l1==l3!=l2:
    print('O triângulo é Isóceles')
  else:
    print('O triângulo é Escaleno')
else:
  print('Não é um triângulo')

"""#### Questão 12
Um estabelecimento está vendendo combustíveis com descontos variados. Para o etanol, se a quantidade comprada for até 15 litros, o desconto será de 2% por litro. Caso contrário, será de 4% por litro. Para o diesel, se a quantidade comprada for até 15 litros, o desconto será de 3% por litro. Caso contrário, será de 5% por litro. O preço do litro de diesel é R\$ 2,00 e o preço do litro de etanol é R\$ 1,70. Escreva um programa que leia a quantidade de litros vendidos e o tipo de combustível (E para etanol e D para diesel) e calcule o valor a ser pago pelo cliente. Tenha em mente algumas dicas:

- O do valor do desconto será a multiplicação entre preço do litro, quantidade de litros e o valor do desconto.
- O valor a ser pago por um cliente será o resultado da multiplicação do preço do litro pela quantidade de litros menos o valor de desconto resultante do cálculo.

"""

litros = int(input('Quantos litros foram vendidos? '))
tipo = input('Etanol ou Diesel? ')
if tipo.upper() == 'ETANOL':
  if litros <= 15:
    disconto = 2 * litros * 0.02
    E = 2 * litros - disconto
    print(f'O valor total é de: {E}')
  else:
    disconto = 2 * litros * 0.04
    E = 2 * litros - disconto
    print(f'O valor total é de: {E}')
elif tipo.upper() == 'DIESEL':
  if litros <= 15:
    disconto = 1.7 * litros * 0.03
    D = 1.7 * litros - disconto
    print(f'O valor total é de: {D}')
  else:
    disconto = 1.7 * litros * 0.05
    D = 1.7 * litros - disconto
    print(f'O valor total é de: {D}')
else: print('Valores inválidos')

"""#### Questão 13
Em uma empresa de venda de imóveis você precisa criar um código que analise os dados de vendas anuais para ajudar a diretoria na tomada de decisão. O código precisa coletar os dados de quantidade de venda durante os anos de 2022 e 2023 e fazer um cálculo de variação percentual. A partir do valor da variação, deve ser enviada às seguintes sugestões:
- Para variação acima de 20%: bonificação para o time de vendas.
- Para variação entre 2% e 20%: pequena bonificação para time de vendas.
- Para variação entre 2% e -10%: planejamento de políticas de incentivo às vendas.
- Para bonificações abaixo de -10%: corte de gastos.

"""

ano_1 = int(input('Insira o valor de vendas de 2022: '))
ano_2 = int(input('Insira o valor de vendas de 2023: '))
porcentual = 100 * (ano_2 - ano_1)/ano_1
if porcentual > 20:
  print('Bonificação para o time de vendas!')
elif 2<=porcentual<=20:
  print('Pequena bonificação para o time de vendas')
elif -10<=porcentual<2:
  print('Planejamento de políticas de incentivo às vendas')
else:
  print('Corte de gastos')

"""## Aula 4 - Estruturas de repetição

### Aquecendo na programação

#### Questão 1
Escreva um programa que peça dois números inteiros e imprima todos os números inteiros entre eles.
"""

n1 = int(input('Primeiro número inteiro: '))
n2 = int(input('Segundo número inteiro: '))
if n1 > n2:
  for n in range(n2 + 1, n1):
    print(n)
    n2 += 1
elif n2 > n1:
  for n in range(n1 + 1, n2):
    print(n)
    n1 += 1
else:
  print('Os números são iguais')

"""#### Questão 2
Escreva um programa para calcular quantos dias levará para a colônia de uma bactéria A ultrapassar ou igualar a colônia de uma bactéria B, com base nas taxas de crescimento de 3% e 1,5% respectivamente. Considere que a colônia A inicia com 4 elementos e a colônia B com 10 elementos.
"""

A = 4
B = 10
dias = 0
while A < B:
  A *= 1.03
  B *= 1.015
  dias += 1
print(f'Levará {dias} dias')

"""#### Questão 3
Para tratar uma quantidade de 15 dados de avaliações de pessoas usuárias de um serviço da empresa, precisamos verificar se as notas são válidas. Então, escreva um programa que vai receber a nota de 0 a 5 de todos os dados e verificar se é um valor válido. Caso seja inserido uma nota acima de 5 ou abaixo de 0, repita até que a pessoa usuária insira um valor válido.
"""

for n in range(15):
  dado = int(input('Insira sua avaliação: '))
  while dado < 0 or dado > 5:
    dado = int(input('Nota inválida, insira novamente: '))
print('Todos os valores validados.')

"""#### Questão 4
Desenvolva um programa que leia um conjunto indeterminado de temperaturas em Celsius e faça uma análise. Portanto, escreva um programa que leia temperaturas e informe a média delas. A leitura deve ser encerrada ao ser enviado o valor -273°C.
"""

temp = float(input('Insira a temperatura: '))
total = 0
contador = 0
while temp != -273:
  total += temp
  contador += 1
  temp = float(input('Insira a temperatura: '))
media = total / contador
print(f'A média das temperaturas foi de {media}')

"""#### Questão 5
Escreva um programa que calcule o fatorial de um número inteiro fornecido pela pessoa usuária. O fatorial de um número inteiro é a multiplicação desse número por todos os seus antecessores até o número 1. Por exemplo, o fatorial de 5 é 5 x 4 x 3 x 2 x 1 = 120.
"""

num = int(input('Insira um número: '))
while num < 0:
  num = int(input('Número inválido, insira um outro número: '))
for n in range(1, num):
  num *= n
print(num)

"""### Momento dos projetos

#### Questão 6
Escreva um programa que gere a tabuada de um número inteiro de 1 a 10, de acordo com a escolha da pessoa usuária. Como exemplo, para o número 2, a tabuada deve ser mostrada no seguinte formato:
```
Tabuada do 2:
2 x 1 = 2
2 x 2 = 4
[...]
2 x 10 = 20
```
"""

numero = int(input('Insira um número de 1 a 10: '))
while numero < 1 or numero > 10:
  numero = int(input('Numero inválido, insira novamente: '))
for n in range(1, 11):
  multi = numero * n
  print(f'{numero} x {n} = {multi}')

"""#### Questão 7
Os números primos possuem várias aplicações dentro da Ciência de Dados, por exemplo, na criptografia e segurança. Um número primo é aquele que é divisível apenas por um e por ele mesmo. Faça um programa que peça um número inteiro e determine se ele é ou não um número primo.
"""

num = int(input('Insira um número: '))
primo = True
if num <=1:
  primo = False
else:
  for n in range(2, num):
    if num % n == 0:
      primo = False
      break
    else:
      primo = True
if primo == False:
  print(f'{num} não é um número primo.')
else:
  print(f'{num} é um número primo.')

"""#### Questão 8
Vamos entender a distribuição de idades de pensionistas de uma empresa de previdência. Escreva um programa que leia as idades de uma quantidade não informada de clientes e mostre a distribuição em intervalos de [0-25], [26-50], [51-75] e [76-100]. Encerre a entrada de dados com um número negativo.
"""

contador1 = 0
contador2 = 0
contador3 = 0
contador4 = 0
while True:
  idade = int(input('Insira a idade, ou um número negativo para encerrar: '))
  while idade > 100:
    int(input('Valor inválido, insira novamente, ou um número negativo para encerrar: '))
  if idade >= 0 and idade <= 25:
    contador1 +=1
  elif idade >= 26 and idade <= 50:
    contador2 +=1
  elif idade >= 51 and idade <= 75:
    contador3 +=1
  elif idade >= 76 and idade <= 100:
    contador4 +=1
  else:
    break
print(f'[0-25]: {contador1}')
print(f'[26-50]: {contador2}')
print(f'[51-75]: {contador3}')
print(f'[51-75]: {contador4}')

"""#### Questão 9
Em uma eleição para gerência em uma empresa com 20 funcionários, existem quatro candidatos. Escreva um programa que calcule o vencedor da eleição. A votação ocorreu da seguinte maneira:
- Cada funcionário votou em um dos quatro candidatos (representados pelos números 1, 2, 3 e 4).
- Também foram contabilizados os votos nulos (representado pelo número 5) e os votos em branco (representado pelo número 6).

Ao final da votação, o programa deve exibir o total de votos para cada candidato, o número de votos nulos e o número de votos em branco. Além disso, deve calcular e exibir a porcentagem de votos nulos em relação ao total de votos e a porcentagem de votos em branco em relação ao total de votos.
"""

candidato1 = 0
candidato2 = 0
candidato3 = 0
candidato4 = 0
nulo = 0
branco = 0
for n in range(20):
  voto = int(input('Informe seu voto: '))
  while voto < 1 or voto > 6:
    voto = int(input('Informe seu voto novamente: '))
  if voto == 1:
    candidato1 +=1
  elif voto == 2:
    candidato2 +=1
  elif voto == 3:
    candidato3 +=1
  elif voto == 4:
    candidato4 +=1
  elif voto == 5:
    nulo +=1
  elif voto == 6:
    branco +=1
print(f'Número de votos do candidato 1: {candidato1}')
print(f'Número de votos do candidato 2: {candidato2}')
print(f'Número de votos do candidato 3: {candidato3}')
print(f'Número de votos do candidato 4: {candidato4}')
print(f'Número de votos nulos: {nulo}')
print(f'Número de votos em brancos: {branco}')
nulo_votos = (100*nulo)/20
print(f'{nulo_votos}% dos votos foram nulos')
branco_votos = (100*branco)/20
print(f'{branco_votos}% dos votos foram em branco')

"""## Aula 5 - Estruturas de dados

### Aquecendo na programação

#### Questão 1
Faça um programa que tenha a seguinte lista contendo os valores de gastos de uma empresa de papel `[2172.54, 3701.35, 3518.09, 3456.61, 3249.38, 2840.82, 3891.45, 3075.26, 2317.64, 3219.08]`. Com esses valores, faça um programa que calcule a média de gastos. Dica, use as funções built-in [`sum()`](https://docs.python.org/3/library/functions.html#sum) e [`len()`](https://docs.python.org/3/library/functions.html#len).
"""

gastos = [2172.54, 3701.35, 3518.09, 3456.61, 3249.38, 2840.82, 3891.45, 3075.26, 2317.64, 3219.08]
media = sum(gastos)/len(gastos)
media

"""#### Questão 2
 Com os mesmos dados da questão anterior, defina quantas compras foram acima de 3000 reais e calcule a porcentagem quanto ao total de compras.
"""

contador = 0
for e in gastos:
  if e > 3000:
    contador +=1
porcent = (contador/len(gastos)) * 100
print(f'{porcent}%')

"""#### Questão 3
Faça um código que colete em uma lista 5 números inteiros quaisquer e imprima a lista. Exemplo: `[1,4,7,2,4]`.
"""

lista_numeros = []
for n in range(5):
  numero = int(input('Digite um número: '))
  lista_numeros.append(numero)
lista_numeros

"""#### Questão 4
Colete novamente 5 inteiros e imprima a lista em ordem inversa à enviada.
"""

lista_numeros = []
for n in range(5):
  numero = int(input('Digite um número: '))
  lista_numeros.append(numero)
lista_numeros.reverse
lista_numeros

"""#### Questão 5
Faça um programa que, ao inserir um número qualquer, criará uma lista contendo todos os números primos entre 1 e o número digitado.
"""

num = int(input('Digite um número: '))
lista = []
primo = True
for n in range(1, num):
  for e in range(1,num):
    if n / e == n or n / e == 1:
      primo = True
    else:
      primo = False
    if primo == True:
      lista.append(n)
lista

"""#### Questão 6
Escreva um programa que peça uma data informando o dia, mês e ano e determine se ela é uma data válida para uma análise.
"""

dia = int(input('Informe o dia: '))
mes = int(input('Informe o mes: '))
ano = int(input('Informe o ano: '))
if dia < 1 or dia > 31:
  analise = False
elif mes < 1 or mes > 12:
  analise = False
elif ano < 1 or ano > 2026:
  analise = False
else:
  analise = True
if analise == True:
  print('Data válida.')
else:
  print('Data inválida.')

"""### Momento dos projetos

#### Questão 7
Para um estudo envolvendo o nível de multiplicação de bactérias em uma colônia, foi coletado o número de bactérias multiplicadas por dia, com base em um processo de duplicação diária e pode ser observado a seguir: `[1.2, 2.1, 3.3, 5.0, 7.8, 11.3, 16.6, 25.1, 37.8, 56.9]`. Tendo esses valores, faça um código que gere uma lista contendo o percentual de crescimento de bactérias por dia, comparando o número de bactérias em cada dia com o número de bactérias do dia anterior. Dica: para calcular o percentual de crescimento usamos a seguinte equação: `100 * (amostra_atual - amostra_passada) / (amostra_passada)`.
"""

bact = [1.2, 2.1, 3.3, 5.0, 7.8, 11.3, 16.6, 25.1, 37.8, 56.9]
percentuais = []
for i in range(1, len(bact)):
  porc = round(100 * (bact[i] - bact[i-1]) / bact[i-1], 2)
  percentuais.append(porc)
percentuais

"""#### Questão 8
Para uma seleção de produtos alimentícios, precisamos separar o conjunto de IDs dados por números inteiros, sabendo que os produtos com ID par são doces e os com ID ímpar são amargos. Monte um código que colete 10 IDs. Depois, calcule e mostre a quantidade de produtos doces e amargos.
"""

amargo = []
doce = []
for n in range(10):
  id = int(input('Insira o ID: '))
  if id % 2 == 0:
    doce.append(id)
  else:
    amargo.append(id)
print(f'Quantidade de amargos:', {len(amargo)}, '. Quantidade de doces:', {len(doce)})

"""#### Questão 9
Desenvolva um programa que informa a nota de um aluno de acordo com suas respostas. Ele deve pedir a resposta de um aluno para cada questão e é preciso verificar se a resposta foi igual ao gabarito. Cada questão vale um ponto e existem alternativas:  A, B, C ou D.
```
Gabarito da Prova:
01 - D
02 - A
03 - C
04 - B
05 - A
06 - D
07 - C
08 - C
09 - A
10 - B
```
"""

gabarito = ['D', 'A', 'C', 'B', 'A', 'D', 'C', 'C', 'A', 'B']
contador = 0
for nota in gabarito:
  resp = input('Insira a resposta da questão: ')
  if resp == nota:
    contador += 1
print(f'Nota:{contador}')

"""#### Questão 10
Um instituto de meteorologia deseja fazer um estudo de temperatura média de cada mês do ano. Para isso, você precisa fazer um código que colete e armazene essas temperaturas médias em uma lista. Depois, calcule a média anual das temperaturas e mostre todas as temperaturas acima da média anual, e em que mês elas ocorreram, mostrando os meses por extenso: Janeiro, Fevereiro, etc.
"""

temps = []
mes_maior = []
meses = ['Janeiro', 'Fevereiro','Março','Abril','Maio','Junho','Julho','Agosto','Setembro','Outubro','Novembro','Dezembro']
for n in range(12):
  temp = float(input('Insira a temperatura: '))
  temps.append(temp)
media = sum(temps)/len(temps)
for e in range(0,12):
  if temps[e] > media:
    mes_maior.append(meses[e])
print(f'A média anual foi dee {media}, e os meses acima da média foram: {mes_maior}')

"""#### Questão 11
Uma empresa de e-commerce está interessada em analisar as vendas dos seus produtos. Os dados das vendas foram armazenados em um dicionário:
```
{'Produto A': 300, 'Produto B': 80, 'Produto C': 60,
 'Produto D': 200, 'Produto E': 250, 'Produto F': 30}
```
Escreva um código que calcule o total de vendas e o produto mais vendido.
"""

vendas = {'Produto A': 300, 'Produto B': 80, 'Produto C': 60,
 'Produto D': 200, 'Produto E': 250, 'Produto F': 30}
mais_vendas = 0
for n in vendas.values():
  if n > mais_vendas:
    mais_vendas = n
for c, v in vendas.items():
  if v == mais_vendas:
    produto_mais_vendido = c
soma = sum(vendas.values())
print(f'O total de vendas é {soma} e o produto mais vendido foi o {produto_mais_vendido}')

"""#### Questão 12
Uma pesquisa de mercado foi feita para decidir qual design de uma marca infantil mais agrada crianças. A pesquisa foi feita e o votos computados podem ser observados abaixo:
```
'''
Tabela de votos da marca
Design 1 - 1334 votos
Design 2 - 982 votos
Design 3 - 1751 votos
Design 4 - 210 votos
Design 5 - 1811 votos
'''
```
Adapte os dados fornecidos a você para uma estrutura de dicionário e a partir dele, informe o design vencedor e a porcentagem de votos recebidos.

"""

votos = {'Design 1': 1334,
         'Design 2': 982,
         'Design 3': 1751,
         'Design 4': 210,
         'Design 5': 1811}
mais_votos = 0
for n in votos.values():
  if n > mais_votos:
    mais_votos = n
for c,v in votos.items():
  if v == mais_votos:
    vencedor = c
porc = (100*mais_votos)/sum(votos.values())
print(f'O vencedor foi {vencedor}, com uma porcentagem de {porc:.2f} dos votos totais.')

"""#### Questão 13
Os funcionários de um setor da empresa que você trabalha vão receber um abono correspondente a 10% do seu salário devido ao ótimo desempenho do time. O setor financeiro solicitou sua ajuda para a verificação das consequências financeiras que esse abono irá gerar nos recursos. Assim, foi encaminhada para você uma lista com os salários que receberão o abono: `[1172, 1644, 2617, 5130, 5532, 6341, 6650, 7238, 7685, 7782, 7903]`. O abono de cada funcionário não pode ser inferior a 200. Em código, transforme cada um dos salários em chaves de um dicionário e o abono de cada salário no elemento. Depois, informe o total de gastos com o abono, quantos funcionários receberam o abono mínimo e qual o maior valor de abono fornecido.

"""

salarios = [1172, 1644, 2617, 5130, 5532, 6341, 6650, 7238, 7685, 7782, 7903]
salarios_abonos = {}
for n in salarios:
  abono = n *0.10
  if abono < 200:
    abono = 200
  salarios_abonos[n] = abono
total_gasto = sum(salarios_abonos.values())
abonos_min = 0
for n in salarios_abonos.values():
  if n == 200:
    abonos_min += 1
abonos_max = max(salarios_abonos.values())
print(f'O total gasto com abonos foi de {total_gasto}, {abonos_min} funcionários receberam o abono mínimo e o maior valor de abono foi {abonos_max}')

"""#### Questão 14
Uma equipe de cientistas de dados está estudando a diversidade biológica em uma floresta. A equipe fez a coleta de informações sobre o número de espécies de plantas e animais em cada área da floresta e armazenaram essas informações em um dicionário. Nele, a chave descreve a área dos dados e os valores nas listas correspondem às espécies de plantas e animais nas áreas, respectivamente.
```
{'Área Norte': [2819, 7236],
 'Área Leste': [1440, 9492],
 'Área Sul': [5969, 7496],
 'Área Oeste': [14446, 49688],
 'Área Centro': [22558, 45148]}
```
Escreva um código para calcular a média de espécies por área e identificar a área com a maior diversidade biológica. Dica: use as funções built-in [`sum()`](https://docs.python.org/3/library/functions.html#sum) e [`len()`](https://docs.python.org/3/library/functions.html#len).

"""

info = {'Área Norte': [2819, 7236],
 'Área Leste': [1440, 9492],
 'Área Sul': [5969, 7496],
 'Área Oeste': [14446, 49688],
 'Área Centro': [22558, 45148]}
maior_bio = 0
medias = {}
for x, y in info.items():
  media = sum(y)/len(y)
  medias[x] = media
  if media > maior_bio:
    maior_area = x
print(medias, f'A área com maio biodiversidade é a {maior_area}')

"""#### Questão 15
O setor de RH da sua empresa te pediu uma ajuda para analisar as idades dos funcionários de 4 setores da empresa. Para isso, ele te forneceu os seguintes dados:
```
{'Setor A': [22, 26, 30, 30, 35, 38, 40, 56, 57, 65],
 'Setor B': [22, 24, 26, 33, 41, 49, 50, 54, 60, 64],
 'Setor C': [23, 26, 26, 29, 34, 35, 36, 41, 52, 56],
 'Setor D': [19, 20, 25, 27, 34, 39, 42, 44, 50, 65]}
```
Sabendo que cada setor tem 10 funcionários, construa um código que calcule a média de idade de cada setor, a idade média geral entre todos os setores e quantas pessoas estão acima da idade média geral.

"""

setores = {'Setor A': [22, 26, 30, 30, 35, 38, 40, 56, 57, 65],
 'Setor B': [22, 24, 26, 33, 41, 49, 50, 54, 60, 64],
 'Setor C': [23, 26, 26, 29, 34, 35, 36, 41, 52, 56],
 'Setor D': [19, 20, 25, 27, 34, 39, 42, 44, 50, 65]}
medias = {}
for x, y in setores.items():
  media = sum(y)/len(y)
  medias[x] = media
media_geral = sum(medias.values())/len(medias.values())
acima_geral = 0
for x, y in setores.items():
  for i in y:
    if i > media_geral:
      acima_geral += 1
print(f'Médias por setor: {medias}', f'A média geral foi de {media_geral} e {acima_geral} pessoas estão acima da média geral.')